  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: backend
    template:
      metadata:
        labels:
          app: backend
      spec:
        containers:
          - name: backend
            image: backend-foodexplorer-image:latest
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 5000
            env:
              - name: SERVER_PORT
                value: "5000"
